on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker build -f Dockerfile.test . --rm  -t app-flask-test
      - name: Run tests
        run: docker run --rm app-flask-test
  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage tests
        run: COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_TOKEN }} sh coverage.sh