on:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - '**'
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: users


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker build -f Dockerfile.test . --rm  -t app-flask-test
      - name: Run tests
        run: docker run --rm app-flask-test
  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage tests
        run: COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_TOKEN }} sh coverage.sh
  deploy:
    if: github.ref == 'master'
    needs: tests
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

        # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v1
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

        # Configure gcloud CLI
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID
        # Build and push image to Google Container Registry
      - name: Build
        run: |
          gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
        # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed