on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker build -f Dockerfile.test . --rm  -t app-flask-test
      - name: Run tests
        run: docker run --rm app-flask-test